version: '3'

services:
  backend:
    build:
      context: .
    volumes:
      - ./app:/backend/app

  webserver:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
